[package]
name = "bar-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9.5", package = "gtk4", features = ["v4_16"] }
gtk4-layer-shell = "0.4.0"
librsvg = "2.59.2"
time = { version = "0.3.37", features = ["formatting", "local-offset"] }
